@url = http://localhost:8080/api

###

# login (normal user)
POST {{url}}/security/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "m-edgeworth", 
    "password": "password"
}

###

# login (admin user)
POST {{url}}/security/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "k-gavin", 
    "password": "password"
}