@url = http://localhost:8080/api
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJrb2FsYS1jaGF0Iiwic3ViIjoiYWRtaW4tcGVyc29uIiwiYXV0aG9yaXRpZXMiOiJST0xFX0FkbWluIiwiZXhwIjoxNjQyNDU0NjY2fQ.0rLfoz8NyHz8DMRKBQmH1uz7zHb3z16-8FvEFaTivFU



###

# login (normal user)
POST {{url}}/security/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "user-person", 
    "password": "password"
}

###

# login (admin user)
POST {{url}}/security/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "admin-person", 
    "password": "password"
}

###

# get all users (admin only)
GET {{url}}/user/all HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# update location
PUT {{url}}/user/location HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "latitude": "25.00", 
    "longitude": "50.00"
}

###

# view all friends
GET {{url}}/user/friend HTTP/1.1
Authorization: Bearer {{token}}

###

# search for new friends
GET {{url}}/user/friend/not HTTP/1.1
Authorization: Bearer {{token}}

###

#add friendship
POST {{url}}/user/friend/add HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

third-person

###

#delete friendship
DELETE {{url}}/user/friend/remove HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

admin-person

###

#view all conversations

GET {{url}}/user/conversation HTTP/1.1
Authorization: Bearer {{token}}

###

#create a conversation
POST {{url}}/user/conversation/add HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "participants": ["user-person", "fourth-person"], 
    "name": "another conversation"
}
###

#find a specifc conversation + attached messages

GET {{url}}/user/conversation/1 HTTP/1.1
Authorization: Bearer {{token}}

###

#disable a user

PUT {{url}}/user/disable/third-person HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

false

